### ISSUE TITLE
Property error on type "DockerService"

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#3]
Introduced by 344d4691d68892d6cb963db335a55e28bbfa223a

```
ERROR in src/app/app.component.ts(18,17): error TS2339: Property 'reveal' does not exist on type 'DockerService'.
```

**Comment by CDuPlooy** [comment]
I'm busy moving things around to the directory structure used by Compiax, those changes should also close this.
